// Generated by npm run db:types from the test database. Do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      ai_runs: {
        Row: {
          control_version: number;
          conversation_id: string;
          created_at: string;
          duration_ms: number | null;
          error_code: string | null;
          estimated_cost_usd: number | null;
          finished_at: string | null;
          handoff_reason: string | null;
          id: string;
          input_tokens: number;
          model_id: string;
          organization_epoch: number;
          organization_id: string;
          output_tokens: number;
          processing_generation: number;
          prompt_version: string;
          public_evidence: Json | null;
          result_summary: string | null;
          run_key: string;
          started_at: string | null;
          status: string;
          tool_call_count: number;
          trigger_message_id: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          control_version: number;
          conversation_id: string;
          created_at?: string;
          duration_ms?: number | null;
          error_code?: string | null;
          estimated_cost_usd?: number | null;
          finished_at?: string | null;
          handoff_reason?: string | null;
          id?: string;
          input_tokens?: number;
          model_id: string;
          organization_epoch: number;
          organization_id: string;
          output_tokens?: number;
          processing_generation: number;
          prompt_version: string;
          public_evidence?: Json | null;
          result_summary?: string | null;
          run_key: string;
          started_at?: string | null;
          status: string;
          tool_call_count?: number;
          trigger_message_id: string;
          updated_at?: string;
        };
        Update: {
          control_version?: number;
          conversation_id?: string;
          created_at?: string;
          duration_ms?: number | null;
          error_code?: string | null;
          estimated_cost_usd?: number | null;
          finished_at?: string | null;
          handoff_reason?: string | null;
          id?: string;
          input_tokens?: number;
          model_id?: string;
          organization_epoch?: number;
          organization_id?: string;
          output_tokens?: number;
          processing_generation?: number;
          prompt_version?: string;
          public_evidence?: Json | null;
          result_summary?: string | null;
          run_key?: string;
          started_at?: string | null;
          status?: string;
          tool_call_count?: number;
          trigger_message_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_runs_organization_id_conversation_id_fkey";
            columns: ["organization_id", "conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "ai_runs_organization_id_conversation_id_trigger_message_id_fkey";
            columns: [
              "organization_id",
              "conversation_id",
              "trigger_message_id",
            ];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["organization_id", "conversation_id", "id"];
          },
          {
            foreignKeyName: "ai_runs_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_tool_calls: {
        Row: {
          ai_run_id: string;
          call_key: string;
          created_at: string;
          error_code: string | null;
          finished_at: string | null;
          id: string;
          operation_key: string;
          organization_id: string;
          result: Json | null;
          status: string;
          tool_name: string;
          updated_at: string;
          validated_arguments: NonNullable<Json>;
        };
        ComputedFields: never;
        Insert: {
          ai_run_id: string;
          call_key: string;
          created_at?: string;
          error_code?: string | null;
          finished_at?: string | null;
          id?: string;
          operation_key: string;
          organization_id: string;
          result?: Json | null;
          status?: string;
          tool_name: string;
          updated_at?: string;
          validated_arguments: NonNullable<Json>;
        };
        Update: {
          ai_run_id?: string;
          call_key?: string;
          created_at?: string;
          error_code?: string | null;
          finished_at?: string | null;
          id?: string;
          operation_key?: string;
          organization_id?: string;
          result?: Json | null;
          status?: string;
          tool_name?: string;
          updated_at?: string;
          validated_arguments?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "ai_tool_calls_organization_id_ai_run_id_fkey";
            columns: ["organization_id", "ai_run_id"];
            isOneToOne: false;
            referencedRelation: "ai_runs";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "ai_tool_calls_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_events: {
        Row: {
          action: string;
          actor_kind: string;
          actor_user_id: string | null;
          changes: NonNullable<Json>;
          created_at: string;
          entity_id: string | null;
          entity_type: string;
          id: string;
          operation_key: string | null;
          organization_id: string;
        };
        ComputedFields: never;
        Insert: {
          action: string;
          actor_kind: string;
          actor_user_id?: string | null;
          changes: NonNullable<Json>;
          created_at?: string;
          entity_id?: string | null;
          entity_type: string;
          id?: string;
          operation_key?: string | null;
          organization_id: string;
        };
        Update: {
          action?: string;
          actor_kind?: string;
          actor_user_id?: string | null;
          changes?: NonNullable<Json>;
          created_at?: string;
          entity_id?: string | null;
          entity_type?: string;
          id?: string;
          operation_key?: string | null;
          organization_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_events_organization_id_actor_user_id_fkey";
            columns: ["organization_id", "actor_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "audit_events_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      channels: {
        Row: {
          created_at: string;
          environment: string;
          id: string;
          kind: string;
          label: string;
          organization_id: string;
          provider_phone_number_id: string | null;
          public_phone_e164: string | null;
          status: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          environment: string;
          id?: string;
          kind: string;
          label: string;
          organization_id: string;
          provider_phone_number_id?: string | null;
          public_phone_e164?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          environment?: string;
          id?: string;
          kind?: string;
          label?: string;
          organization_id?: string;
          provider_phone_number_id?: string | null;
          public_phone_e164?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "channels_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      contacts: {
        Row: {
          archived_at: string | null;
          created_at: string;
          demo_key: string | null;
          display_name: string | null;
          id: string;
          organization_id: string;
          phone_e164: string | null;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          demo_key?: string | null;
          display_name?: string | null;
          id?: string;
          organization_id: string;
          phone_e164?: string | null;
          updated_at?: string;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          demo_key?: string | null;
          display_name?: string | null;
          id?: string;
          organization_id?: string;
          phone_e164?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "contacts_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      conversations: {
        Row: {
          active_message_id: string | null;
          channel_id: string;
          control_version: number;
          created_at: string;
          handoff_completed_at: string | null;
          handoff_reason: string | null;
          handoff_requested_at: string | null;
          handoff_requested_by_user_id: string | null;
          handoff_status: string;
          id: string;
          last_customer_message_at: string | null;
          lead_id: string;
          mode: string;
          next_inbound_sequence: number;
          organization_id: string;
          processed_through_sequence: number;
          processing_generation: number;
          processing_lease_expires_at: string | null;
          processing_token: string | null;
          status: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          active_message_id?: string | null;
          channel_id: string;
          control_version?: number;
          created_at?: string;
          handoff_completed_at?: string | null;
          handoff_reason?: string | null;
          handoff_requested_at?: string | null;
          handoff_requested_by_user_id?: string | null;
          handoff_status?: string;
          id?: string;
          last_customer_message_at?: string | null;
          lead_id: string;
          mode?: string;
          next_inbound_sequence?: number;
          organization_id: string;
          processed_through_sequence?: number;
          processing_generation?: number;
          processing_lease_expires_at?: string | null;
          processing_token?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          active_message_id?: string | null;
          channel_id?: string;
          control_version?: number;
          created_at?: string;
          handoff_completed_at?: string | null;
          handoff_reason?: string | null;
          handoff_requested_at?: string | null;
          handoff_requested_by_user_id?: string | null;
          handoff_status?: string;
          id?: string;
          last_customer_message_at?: string | null;
          lead_id?: string;
          mode?: string;
          next_inbound_sequence?: number;
          organization_id?: string;
          processed_through_sequence?: number;
          processing_generation?: number;
          processing_lease_expires_at?: string | null;
          processing_token?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversations_organization_id_channel_id_fkey";
            columns: ["organization_id", "channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "conversations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_organization_id_handoff_requested_by_user_id_fkey";
            columns: ["organization_id", "handoff_requested_by_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "conversations_organization_id_id_active_message_id_fkey";
            columns: ["organization_id", "id", "active_message_id"];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["organization_id", "conversation_id", "id"];
          },
          {
            foreignKeyName: "conversations_organization_id_lead_id_fkey";
            columns: ["organization_id", "lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      job_outbox: {
        Row: {
          conversation_id: string | null;
          created_at: string;
          dispatch_attempts: number;
          dispatch_status: string;
          execution_status: string;
          finished_at: string | null;
          id: string;
          kind: string;
          last_error_code: string | null;
          last_run_activity_at: string;
          next_dispatch_at: string;
          next_run_at: string;
          operation_key: string;
          organization_epoch: number;
          organization_id: string;
          payload: NonNullable<Json>;
          publish_lease_expires_at: string | null;
          publish_token: string | null;
          published_at: string | null;
          run_attempts: number;
          run_lease_expires_at: string | null;
          run_token: string | null;
          started_at: string | null;
          updated_at: string;
          webhook_event_id: string | null;
        };
        ComputedFields: never;
        Insert: {
          conversation_id?: string | null;
          created_at?: string;
          dispatch_attempts?: number;
          dispatch_status?: string;
          execution_status?: string;
          finished_at?: string | null;
          id?: string;
          kind: string;
          last_error_code?: string | null;
          last_run_activity_at?: string;
          next_dispatch_at?: string;
          next_run_at?: string;
          operation_key: string;
          organization_epoch: number;
          organization_id: string;
          payload: NonNullable<Json>;
          publish_lease_expires_at?: string | null;
          publish_token?: string | null;
          published_at?: string | null;
          run_attempts?: number;
          run_lease_expires_at?: string | null;
          run_token?: string | null;
          started_at?: string | null;
          updated_at?: string;
          webhook_event_id?: string | null;
        };
        Update: {
          conversation_id?: string | null;
          created_at?: string;
          dispatch_attempts?: number;
          dispatch_status?: string;
          execution_status?: string;
          finished_at?: string | null;
          id?: string;
          kind?: string;
          last_error_code?: string | null;
          last_run_activity_at?: string;
          next_dispatch_at?: string;
          next_run_at?: string;
          operation_key?: string;
          organization_epoch?: number;
          organization_id?: string;
          payload?: NonNullable<Json>;
          publish_lease_expires_at?: string | null;
          publish_token?: string | null;
          published_at?: string | null;
          run_attempts?: number;
          run_lease_expires_at?: string | null;
          run_token?: string | null;
          started_at?: string | null;
          updated_at?: string;
          webhook_event_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "job_outbox_organization_id_conversation_id_fkey";
            columns: ["organization_id", "conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "job_outbox_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "job_outbox_organization_id_webhook_event_id_fkey";
            columns: ["organization_id", "webhook_event_id"];
            isOneToOne: false;
            referencedRelation: "webhook_events";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      knowledge_entries: {
        Row: {
          answer: string;
          created_at: string;
          id: string;
          is_active: boolean;
          organization_id: string;
          question: string;
          updated_at: string;
          updated_by_user_id: string | null;
          visibility: string;
        };
        ComputedFields: never;
        Insert: {
          answer: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          organization_id: string;
          question: string;
          updated_at?: string;
          updated_by_user_id?: string | null;
          visibility: string;
        };
        Update: {
          answer?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          organization_id?: string;
          question?: string;
          updated_at?: string;
          updated_by_user_id?: string | null;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: "knowledge_entries_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "knowledge_entries_organization_id_updated_by_user_id_fkey";
            columns: ["organization_id", "updated_by_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
        ];
      };
      leads: {
        Row: {
          assigned_user_id: string | null;
          budget_max_rupiah: number | null;
          budget_min_rupiah: number | null;
          closed_at: string | null;
          contact_id: string;
          created_at: string;
          id: string;
          interested_property_id: string | null;
          min_bedrooms: number | null;
          organization_id: string;
          preferred_area: string | null;
          source_channel_id: string | null;
          source_evidence: string | null;
          source_kind: string;
          source_message_id: string | null;
          stage: string;
          summary: string | null;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          assigned_user_id?: string | null;
          budget_max_rupiah?: number | null;
          budget_min_rupiah?: number | null;
          closed_at?: string | null;
          contact_id: string;
          created_at?: string;
          id?: string;
          interested_property_id?: string | null;
          min_bedrooms?: number | null;
          organization_id: string;
          preferred_area?: string | null;
          source_channel_id?: string | null;
          source_evidence?: string | null;
          source_kind?: string;
          source_message_id?: string | null;
          stage?: string;
          summary?: string | null;
          updated_at?: string;
        };
        Update: {
          assigned_user_id?: string | null;
          budget_max_rupiah?: number | null;
          budget_min_rupiah?: number | null;
          closed_at?: string | null;
          contact_id?: string;
          created_at?: string;
          id?: string;
          interested_property_id?: string | null;
          min_bedrooms?: number | null;
          organization_id?: string;
          preferred_area?: string | null;
          source_channel_id?: string | null;
          source_evidence?: string | null;
          source_kind?: string;
          source_message_id?: string | null;
          stage?: string;
          summary?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "leads_organization_id_assigned_user_id_fkey";
            columns: ["organization_id", "assigned_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "leads_organization_id_contact_id_fkey";
            columns: ["organization_id", "contact_id"];
            isOneToOne: true;
            referencedRelation: "contacts";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "leads_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "leads_organization_id_interested_property_id_fkey";
            columns: ["organization_id", "interested_property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "leads_organization_id_source_channel_id_fkey";
            columns: ["organization_id", "source_channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "leads_organization_id_source_message_id_fkey";
            columns: ["organization_id", "source_message_id"];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      memberships: {
        Row: {
          created_at: string;
          display_name: string;
          is_active: boolean;
          organization_id: string;
          role: string;
          updated_at: string;
          user_id: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          display_name: string;
          is_active?: boolean;
          organization_id: string;
          role: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          display_name?: string;
          is_active?: boolean;
          organization_id?: string;
          role?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "memberships_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      messages: {
        Row: {
          accepted_at: string | null;
          author_kind: string;
          author_user_id: string | null;
          body_text: string;
          channel_id: string;
          content_kind: string;
          conversation_id: string;
          created_at: string;
          delivered_at: string | null;
          delivery_status: string | null;
          direction: string;
          id: string;
          inbound_sequence: number | null;
          organization_id: string;
          processing_status: string | null;
          provider_message_id: string | null;
          provider_timestamp: string | null;
          read_at: string | null;
          received_at: string | null;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          accepted_at?: string | null;
          author_kind: string;
          author_user_id?: string | null;
          body_text: string;
          channel_id: string;
          content_kind?: string;
          conversation_id: string;
          created_at?: string;
          delivered_at?: string | null;
          delivery_status?: string | null;
          direction: string;
          id?: string;
          inbound_sequence?: number | null;
          organization_id: string;
          processing_status?: string | null;
          provider_message_id?: string | null;
          provider_timestamp?: string | null;
          read_at?: string | null;
          received_at?: string | null;
          updated_at?: string;
        };
        Update: {
          accepted_at?: string | null;
          author_kind?: string;
          author_user_id?: string | null;
          body_text?: string;
          channel_id?: string;
          content_kind?: string;
          conversation_id?: string;
          created_at?: string;
          delivered_at?: string | null;
          delivery_status?: string | null;
          direction?: string;
          id?: string;
          inbound_sequence?: number | null;
          organization_id?: string;
          processing_status?: string | null;
          provider_message_id?: string | null;
          provider_timestamp?: string | null;
          read_at?: string | null;
          received_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_organization_id_author_user_id_fkey";
            columns: ["organization_id", "author_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "messages_organization_id_conversation_id_channel_id_fkey";
            columns: ["organization_id", "conversation_id", "channel_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["organization_id", "id", "channel_id"];
          },
          {
            foreignKeyName: "messages_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          created_at: string;
          default_sales_user_id: string | null;
          id: string;
          is_demo: boolean;
          name: string;
          processing_epoch: number;
          processing_paused: boolean;
          slug: string;
          timezone: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          default_sales_user_id?: string | null;
          id?: string;
          is_demo?: boolean;
          name: string;
          processing_epoch?: number;
          processing_paused?: boolean;
          slug: string;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          default_sales_user_id?: string | null;
          id?: string;
          is_demo?: boolean;
          name?: string;
          processing_epoch?: number;
          processing_paused?: boolean;
          slug?: string;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organizations_id_default_sales_user_id_fkey";
            columns: ["id", "default_sales_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
        ];
      };
      outbox: {
        Row: {
          ai_run_id: string | null;
          attempt_count: number;
          claim_token: string | null;
          control_version: number;
          conversation_id: string;
          created_at: string;
          finished_at: string | null;
          id: string;
          last_error_code: string | null;
          message_id: string;
          next_attempt_at: string | null;
          operation_key: string;
          organization_epoch: number;
          organization_id: string;
          request_started_at: string | null;
          status: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          ai_run_id?: string | null;
          attempt_count?: number;
          claim_token?: string | null;
          control_version: number;
          conversation_id: string;
          created_at?: string;
          finished_at?: string | null;
          id?: string;
          last_error_code?: string | null;
          message_id: string;
          next_attempt_at?: string | null;
          operation_key: string;
          organization_epoch: number;
          organization_id: string;
          request_started_at?: string | null;
          status?: string;
          updated_at?: string;
        };
        Update: {
          ai_run_id?: string | null;
          attempt_count?: number;
          claim_token?: string | null;
          control_version?: number;
          conversation_id?: string;
          created_at?: string;
          finished_at?: string | null;
          id?: string;
          last_error_code?: string | null;
          message_id?: string;
          next_attempt_at?: string | null;
          operation_key?: string;
          organization_epoch?: number;
          organization_id?: string;
          request_started_at?: string | null;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "outbox_organization_id_conversation_id_ai_run_id_fkey";
            columns: ["organization_id", "conversation_id", "ai_run_id"];
            isOneToOne: false;
            referencedRelation: "ai_runs";
            referencedColumns: ["organization_id", "conversation_id", "id"];
          },
          {
            foreignKeyName: "outbox_organization_id_conversation_id_fkey";
            columns: ["organization_id", "conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "outbox_organization_id_conversation_id_message_id_fkey";
            columns: ["organization_id", "conversation_id", "message_id"];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["organization_id", "conversation_id", "id"];
          },
          {
            foreignKeyName: "outbox_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      properties: {
        Row: {
          amenities: string[];
          area: string;
          availability: string;
          bathrooms: number;
          bedrooms: number;
          building_area_m2: number | null;
          city: string;
          created_at: string;
          created_by_user_id: string | null;
          description: string;
          id: string;
          land_area_m2: number | null;
          organization_id: string;
          price_rupiah: number;
          property_type: string;
          public_address: string | null;
          public_code: string;
          publication_status: string;
          published_at: string | null;
          seo_description: string | null;
          seo_title: string | null;
          slug: string;
          title: string;
          updated_at: string;
          updated_by_user_id: string | null;
        };
        ComputedFields: never;
        Insert: {
          amenities?: string[];
          area: string;
          availability?: string;
          bathrooms: number;
          bedrooms: number;
          building_area_m2?: number | null;
          city: string;
          created_at?: string;
          created_by_user_id?: string | null;
          description: string;
          id?: string;
          land_area_m2?: number | null;
          organization_id: string;
          price_rupiah: number;
          property_type?: string;
          public_address?: string | null;
          public_code: string;
          publication_status?: string;
          published_at?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug: string;
          title: string;
          updated_at?: string;
          updated_by_user_id?: string | null;
        };
        Update: {
          amenities?: string[];
          area?: string;
          availability?: string;
          bathrooms?: number;
          bedrooms?: number;
          building_area_m2?: number | null;
          city?: string;
          created_at?: string;
          created_by_user_id?: string | null;
          description?: string;
          id?: string;
          land_area_m2?: number | null;
          organization_id?: string;
          price_rupiah?: number;
          property_type?: string;
          public_address?: string | null;
          public_code?: string;
          publication_status?: string;
          published_at?: string | null;
          seo_description?: string | null;
          seo_title?: string | null;
          slug?: string;
          title?: string;
          updated_at?: string;
          updated_by_user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "properties_organization_id_created_by_user_id_fkey";
            columns: ["organization_id", "created_by_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "properties_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "properties_organization_id_updated_by_user_id_fkey";
            columns: ["organization_id", "updated_by_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
        ];
      };
      property_assets: {
        Row: {
          alt_text: string;
          byte_size: number;
          created_at: string;
          id: string;
          is_cover: boolean;
          is_public: boolean;
          mime_type: string;
          organization_id: string;
          property_id: string;
          sort_order: number;
          storage_path: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          alt_text: string;
          byte_size: number;
          created_at?: string;
          id?: string;
          is_cover?: boolean;
          is_public?: boolean;
          mime_type: string;
          organization_id: string;
          property_id: string;
          sort_order: number;
          storage_path: string;
          updated_at?: string;
        };
        Update: {
          alt_text?: string;
          byte_size?: number;
          created_at?: string;
          id?: string;
          is_cover?: boolean;
          is_public?: boolean;
          mime_type?: string;
          organization_id?: string;
          property_id?: string;
          sort_order?: number;
          storage_path?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "property_assets_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "property_assets_organization_id_property_id_fkey";
            columns: ["organization_id", "property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      property_private_details: {
        Row: {
          created_at: string;
          exact_address: string | null;
          internal_notes: string | null;
          organization_id: string;
          owner_name: string | null;
          owner_phone_e164: string | null;
          property_id: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          exact_address?: string | null;
          internal_notes?: string | null;
          organization_id: string;
          owner_name?: string | null;
          owner_phone_e164?: string | null;
          property_id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          exact_address?: string | null;
          internal_notes?: string | null;
          organization_id?: string;
          owner_name?: string | null;
          owner_phone_e164?: string | null;
          property_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "property_private_details_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "property_private_details_organization_id_property_id_fkey";
            columns: ["organization_id", "property_id"];
            isOneToOne: true;
            referencedRelation: "properties";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      site_daily_metrics: {
        Row: {
          count: number;
          event_name: string;
          metric_date: string;
          organization_id: string;
          page_key: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          count?: number;
          event_name: string;
          metric_date: string;
          organization_id: string;
          page_key: string;
          updated_at?: string;
        };
        Update: {
          count?: number;
          event_name?: string;
          metric_date?: string;
          organization_id?: string;
          page_key?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "site_daily_metrics_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      site_settings: {
        Row: {
          about_text: string;
          brand_name: string;
          canonical_origin: string;
          created_at: string;
          cta_channel_id: string | null;
          headline: string;
          indexing_enabled: boolean;
          logo_path: string | null;
          organization_id: string;
          privacy_text: string;
          public_contact_text: string | null;
          seo_description: string;
          seo_title: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          about_text: string;
          brand_name: string;
          canonical_origin: string;
          created_at?: string;
          cta_channel_id?: string | null;
          headline: string;
          indexing_enabled?: boolean;
          logo_path?: string | null;
          organization_id: string;
          privacy_text: string;
          public_contact_text?: string | null;
          seo_description: string;
          seo_title: string;
          updated_at?: string;
        };
        Update: {
          about_text?: string;
          brand_name?: string;
          canonical_origin?: string;
          created_at?: string;
          cta_channel_id?: string | null;
          headline?: string;
          indexing_enabled?: boolean;
          logo_path?: string | null;
          organization_id?: string;
          privacy_text?: string;
          public_contact_text?: string | null;
          seo_description?: string;
          seo_title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "site_settings_organization_id_cta_channel_id_fkey";
            columns: ["organization_id", "cta_channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "site_settings_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: true;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
      surveys: {
        Row: {
          agent_user_id: string;
          cancellation_reason: string | null;
          completed_at: string | null;
          confirmed_at: string | null;
          confirmed_by_user_id: string | null;
          created_at: string;
          ends_at: string;
          id: string;
          lead_id: string;
          operation_key: string;
          organization_id: string;
          property_id: string;
          result_notes: string | null;
          starts_at: string;
          status: string;
          updated_at: string;
          visit_notes: string | null;
        };
        ComputedFields: never;
        Insert: {
          agent_user_id: string;
          cancellation_reason?: string | null;
          completed_at?: string | null;
          confirmed_at?: string | null;
          confirmed_by_user_id?: string | null;
          created_at?: string;
          ends_at: string;
          id?: string;
          lead_id: string;
          operation_key: string;
          organization_id: string;
          property_id: string;
          result_notes?: string | null;
          starts_at: string;
          status?: string;
          updated_at?: string;
          visit_notes?: string | null;
        };
        Update: {
          agent_user_id?: string;
          cancellation_reason?: string | null;
          completed_at?: string | null;
          confirmed_at?: string | null;
          confirmed_by_user_id?: string | null;
          created_at?: string;
          ends_at?: string;
          id?: string;
          lead_id?: string;
          operation_key?: string;
          organization_id?: string;
          property_id?: string;
          result_notes?: string | null;
          starts_at?: string;
          status?: string;
          updated_at?: string;
          visit_notes?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "surveys_organization_id_agent_user_id_fkey";
            columns: ["organization_id", "agent_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "surveys_organization_id_confirmed_by_user_id_fkey";
            columns: ["organization_id", "confirmed_by_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "surveys_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "surveys_organization_id_lead_id_fkey";
            columns: ["organization_id", "lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "surveys_organization_id_property_id_fkey";
            columns: ["organization_id", "property_id"];
            isOneToOne: false;
            referencedRelation: "properties";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      tasks: {
        Row: {
          assigned_user_id: string | null;
          completed_at: string | null;
          conversation_id: string | null;
          created_at: string;
          description: string | null;
          due_at: string;
          id: string;
          kind: string;
          lead_id: string | null;
          operation_key: string;
          organization_id: string;
          status: string;
          title: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          assigned_user_id?: string | null;
          completed_at?: string | null;
          conversation_id?: string | null;
          created_at?: string;
          description?: string | null;
          due_at: string;
          id?: string;
          kind: string;
          lead_id?: string | null;
          operation_key: string;
          organization_id: string;
          status?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          assigned_user_id?: string | null;
          completed_at?: string | null;
          conversation_id?: string | null;
          created_at?: string;
          description?: string | null;
          due_at?: string;
          id?: string;
          kind?: string;
          lead_id?: string | null;
          operation_key?: string;
          organization_id?: string;
          status?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_organization_id_assigned_user_id_fkey";
            columns: ["organization_id", "assigned_user_id"];
            isOneToOne: false;
            referencedRelation: "memberships";
            referencedColumns: ["organization_id", "user_id"];
          },
          {
            foreignKeyName: "tasks_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_organization_id_lead_id_conversation_id_fkey";
            columns: ["organization_id", "lead_id", "conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["organization_id", "lead_id", "id"];
          },
          {
            foreignKeyName: "tasks_organization_id_lead_id_fkey";
            columns: ["organization_id", "lead_id"];
            isOneToOne: false;
            referencedRelation: "leads";
            referencedColumns: ["organization_id", "id"];
          },
        ];
      };
      webhook_events: {
        Row: {
          channel_id: string;
          created_at: string;
          event_key: string;
          event_kind: string;
          id: string;
          last_error_code: string | null;
          message_id: string | null;
          occurred_at: string | null;
          organization_id: string;
          payload: Json | null;
          processed_at: string | null;
          provider_message_id: string | null;
          provider_status: string | null;
          received_at: string;
          status: string;
        };
        ComputedFields: never;
        Insert: {
          channel_id: string;
          created_at?: string;
          event_key: string;
          event_kind: string;
          id?: string;
          last_error_code?: string | null;
          message_id?: string | null;
          occurred_at?: string | null;
          organization_id: string;
          payload?: Json | null;
          processed_at?: string | null;
          provider_message_id?: string | null;
          provider_status?: string | null;
          received_at?: string;
          status?: string;
        };
        Update: {
          channel_id?: string;
          created_at?: string;
          event_key?: string;
          event_kind?: string;
          id?: string;
          last_error_code?: string | null;
          message_id?: string | null;
          occurred_at?: string | null;
          organization_id?: string;
          payload?: Json | null;
          processed_at?: string | null;
          provider_message_id?: string | null;
          provider_status?: string | null;
          received_at?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "webhook_events_organization_id_channel_id_fkey";
            columns: ["organization_id", "channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["organization_id", "id"];
          },
          {
            foreignKeyName: "webhook_events_organization_id_channel_id_message_id_fkey";
            columns: ["organization_id", "channel_id", "message_id"];
            isOneToOne: false;
            referencedRelation: "messages";
            referencedColumns: ["organization_id", "channel_id", "id"];
          },
          {
            foreignKeyName: "webhook_events_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      active_role: { Args: { p_organization_id: string }; Returns: string };
      can_read_lead: {
        Args: { p_lead_id: string; p_organization_id: string };
        Returns: boolean;
      };
      get_property_for_edit: {
        Args: { p_organization_id: string; p_property_id: string };
        Returns: Json;
      };
      save_property: {
        Args: {
          p_data: Json;
          p_organization_id: string;
          p_property_id: string;
        };
        Returns: string;
      };
      search_public_properties: {
        Args: {
          p_bedrooms?: number;
          p_budget?: number;
          p_location?: string;
          p_organization_id: string;
          p_type?: string;
        };
        Returns: {
          amenities: string[];
          area: string;
          bathrooms: number;
          bedrooms: number;
          building_area_m2: string;
          city: string;
          description: string;
          id: string;
          land_area_m2: string;
          price_rupiah: string;
          property_type: string;
          public_code: string;
          slug: string;
          title: string;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
