import { mkdir, writeFile } from "node:fs/promises";
import pg from "pg";
import { introspect, generateTypescript, sortGeneratorMetadata } from "@supabase/postgrest-typegen";
import { format } from "prettier";
import { testDatabaseConfig } from "./test-database";

let client: pg.Pool | undefined;
try {
  client = new pg.Pool({ ...testDatabaseConfig(), max: 2, options: "-c default_transaction_read_only=on" });
  const metadata = sortGeneratorMetadata(await introspect(client, { includedSchemas: ["public"] }));
  if (!metadata.tables.some(table => table.name === "organizations")) throw new Error("Migrasi belum tersedia.");
  const types = await generateTypescript(metadata, {
    detectOneToOneRelationships: true,
    format: source => format(source, { parser: "typescript" }),
  });
  await mkdir(new URL("../src/types/", import.meta.url), { recursive: true });
  await writeFile(new URL("../src/types/database.generated.ts", import.meta.url),
    `// Generated by npm run db:types from the test database. Do not edit.\n${types}`);
  console.log("PASS: src/types/database.generated.ts diperbarui dari schema public.");
} catch {
  console.error("FAIL: db:types. Periksa konfigurasi uji, koneksi, dan migrasi; detail koneksi tidak dicetak.");
  process.exitCode = 1;
} finally {
  await client?.end().catch(() => {});
}
